### ISSUE TITLE
Prev Next page inversed for pages.

### ISSUE THREAD

**Issue by digitalfredy** [sighingnow/jekyll-gitbook#44] opened 2022-07-21 19:38 UTC
# Bug report

First thanks for sharing this great theme :+1: 

## Problem definition

The _<_  and _>_ buttons in the left and right side of the page drive the reader in the reverse order for pages.

## How to reproduce

1. Go to the first page in the menu for the demo site [here](https://sighingnow.github.io/jekyll-gitbook/pages/design/draft/)
2. Notice it will only show the arrow for the "Previous page" while this is the first page
3. Go to any other page in the menu and use the "Previous/Next page" arrows, Next link to the Prev page in the menu

## Expected

Starting in the main page  using next will move to the next item in the left menu, first pages then posts.

## Notes

It works OK for posts.

**Comment by sighingnow** [comment] 2022-07-27 16:33
Fixed in https://github.com/sighingnow/jekyll-gitbook/commit/a104416637e5ddc637bfa0356dbb234a9f782c80

This issue is caused by the different sorting behaviour between collections and `_posts`.

**Closed by sighingnow** 2022-07-27 16:33 UTC
